name: MSYS2 PKGBUILD

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  win-makepkg:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { sys: mingw64, env: x86_64, renderer: poppler, poppler: ON, mupdf: OFF, qt: 5, icon: '🟦' }
          - { sys: mingw64, env: x86_64, renderer: mupdf, poppler: OFF, mupdf: ON, qt: 5, icon: '🟦' }
          - { sys: mingw64, env: x86_64, renderer: poppler, poppler: ON, mupdf: OFF, qt: 6, icon: '🟦' }
          - { sys: mingw64, env: x86_64, renderer: mupdf, poppler: OFF, mupdf: ON, qt: 6, icon: '🟦' }
          - { sys: ucrt64,  env: ucrt-x86_64, renderer: poppler, poppler: ON, mupdf: OFF, qt: 5, icon: '🟨' }
          - { sys: ucrt64,  env: ucrt-x86_64, renderer: mupdf, poppler: OFF, mupdf: ON, qt: 5, icon: '🟨' }
          - { sys: ucrt64,  env: ucrt-x86_64, renderer: poppler, poppler: ON, mupdf: OFF, qt: 6, icon: '🟨' }
          - { sys: ucrt64,  env: ucrt-x86_64, renderer: mupdf, poppler: OFF, mupdf: ON, qt: 6, icon: '🟨' }
          - { sys: clang64, env: clang-x86_64, renderer: poppler, poppler: ON, mupdf: OFF, qt: 5, icon: '🟧' }
          - { sys: clang64, env: clang-x86_64, renderer: mupdf, poppler: OFF, mupdf: ON, qt: 5, icon: '🟧' }
          - { sys: clang64, env: clang-x86_64, renderer: poppler, poppler: ON, mupdf: OFF, qt: 6, icon: '🟧' }
          - { sys: clang64, env: clang-x86_64, renderer: mupdf, poppler: OFF, mupdf: ON, qt: 6, icon: '🟧' }
    name: 🚧${{ matrix.icon }} ${{ matrix.sys }} ${{ matrix.renderer }} qt${{ matrix.qt }} | makepkg
    defaults:
      run:
        shell: msys2 {0}
    env:
      MINGW_ARCH: ${{ matrix.sys }}
      _use_poppler: ${{ matrix.poppler }}
      _use_mupdf: ${{ matrix.mupdf }}
      _qt_version_major: ${{ matrix.qt }}

    steps:
    - name: '🧰 Checkout'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: '${{ matrix.icon }} Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        update: true
        install: git base-devel tree

    - name: '🚧 Build package'
      run: |
        cp packaging/PKGBUILD_MSYS2_git .
        dos2unix PKGBUILD_MSYS2_git
        if [ ${{ matrix.sys }} != clang64 ]; then pacman -S --noconfirm --noprogressbar mingw-w64-${{ matrix.env }}-gcc; else pacman -S --noconfirm --noprogressbar mingw-w64-${{ matrix.env }}-clang; fi
        makepkg-mingw --noconfirm --noprogressbar -sCLfp PKGBUILD_MSYS2_git

    - name: '🛠️ Deploy package'
      run: |
        PKG_FILE=$(find . -name 'mingw-w64-${{ matrix.env }}-beamerpresenter-${{ matrix.renderer }}-qt${{ matrix.qt }}-git-*.pkg.tar.zst')
        rm -rf deploy
        mkdir -p deploy
        tar --zstd -xf "${PKG_FILE}" -C deploy
        rm -f "${PKG_FILE}"
        cd deploy
        rm -f .BUILDINFO .MTREE .PKGINFO
        mv '${{ matrix.sys }}/bin'/* .
        rm -rf '${{ matrix.sys }}/bin'
        mv etc/xdg/beamerpresenter/* .
        rm -rf etc
        echo '.\beamerpresenter.exe -c beamerpresenter.conf -g gui.json' > beamerpresenter.bat
        tar --zstd -cf "../${PKG_FILE}" *

    - name: '📤 Upload artifact: package'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.sys }}-BeamerPresenter-${{ matrix.renderer }}-qt${{ matrix.qt }}
        path: ${{ github.workspace }}/mingw-w64-${{ matrix.env }}-beamerpresenter-${{ matrix.renderer }}-qt${{ matrix.qt }}-git-*.pkg.tar.zst

    - name: '🚦 Test package'
      run: |
        cd deploy
        ./beamerpresenter.exe --version
        cp ../tests/minimal.pdf .
        cp ../tests/minimal.xml .
        dos2unix minimal.pdf
        dos2unix minimal.xml
        timeout 20 ./beamerpresenter.exe --test minimal.pdf
        timeout 20 ./beamerpresenter.exe --test minimal.xml
